title = 'Palico-GameProgrammer'
baseURL = 'https://palico.dev/'
theme = 'Paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'Palico-Dev'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'pengyu-ren-b0b9bb335'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'https://palico.dev/images/palico.jpg'                 # gravatar email or image url
  name = 'Pengyu Ren(Max)'
  bio = 'Game Developer & Game Engine Enthusiast. Currently building a 3D Engine.'


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

  # giscus
[params.giscus]
  mapping = 'pathname'
  theme = 'light'
  lang = 'en-us'